//
// Generated by LLVM NVPTX Back-End
//

.version 3.2
.target sm_20, texmode_independent
.address_size 64

	// .globl	SYCL_class_monte_carlo_pi_kernel // -- Begin function SYCL_class_monte_carlo_pi_kernel
                                        // @SYCL_class_monte_carlo_pi_kernel
.entry SYCL_class_monte_carlo_pi_kernel(
	.param .u64 .ptr .global .align 8 SYCL_class_monte_carlo_pi_kernel_param_0,
	.param .u64 .ptr .global .align 4 SYCL_class_monte_carlo_pi_kernel_param_1,
	.param .u64 .ptr .shared .align 4 SYCL_class_monte_carlo_pi_kernel_param_2
)
{
	.reg .pred 	%p<14>;
	.reg .f32 	%f<20>;
	.reg .b32 	%r<35>;
	.reg .b64 	%rd<36>;

// %bb.0:
	ld.param.u64 	%rd19, [SYCL_class_monte_carlo_pi_kernel_param_2];
	ld.param.u64 	%rd20, [SYCL_class_monte_carlo_pi_kernel_param_0];
	mov.u32 	%r8, %ctaid.x;
	mov.u32 	%r9, %ntid.x;
	mov.u32 	%r10, %tid.x;
	mad.lo.s32 	%r11, %r9, %r8, %r10;
	cvt.u64.u32 	%rd1, %r10;
	mul.wide.u32 	%rd21, %r11, 8;
	add.s64 	%rd22, %rd20, %rd21;
	ld.global.v2.f32 	{%f1, %f2}, [%rd22];
	mul.rn.f32 	%f8, %f2, %f2;
	fma.rn.f32 	%f3, %f1, %f1, %f8;
	setp.geu.f32 	%p1, %f3, 0f00800000;
	@%p1 bra 	LBB0_2;
// %bb.1:
	mul.rn.f32 	%f14, %f1, 0f6A800000;
	mul.rn.f32 	%f15, %f2, 0f6A800000;
	mul.rn.f32 	%f16, %f15, %f15;
	fma.rn.f32 	%f17, %f14, %f14, %f16;
	sqrt.rn.f32 	%f18, %f17;
	mul.rn.f32 	%f19, %f18, 0f14800000;
	bra.uni 	LBB0_5;
LBB0_2:
	setp.neu.f32 	%p2, %f3, 0f7F800000;
	@%p2 bra 	LBB0_4;
// %bb.3:
	mul.rn.f32 	%f9, %f1, 0f1F000000;
	mul.rn.f32 	%f10, %f2, 0f1F000000;
	mul.rn.f32 	%f11, %f10, %f10;
	fma.rn.f32 	%f12, %f9, %f9, %f11;
	sqrt.rn.f32 	%f13, %f12;
	mul.rn.f32 	%f19, %f13, 0f60000000;
	bra.uni 	LBB0_5;
LBB0_4:
	sqrt.rn.f32 	%f19, %f3;
LBB0_5:
	cvt.u32.u64 	%r12, %rd1;
	setp.le.f32 	%p3, %f19, 0f3F800000;
	selp.u32 	%r13, 1, 0, %p3;
	shl.b64 	%rd23, %rd1, 2;
	add.s64 	%rd24, %rd19, %rd23;
	st.shared.u32 	[%rd24], %r13;
	bar.sync 	0;
	setp.ne.s32 	%p4, %r12, 0;
	@%p4 bra 	LBB0_13;
// %bb.6:
	cvt.u64.u32 	%rd3, %r9;
	add.s64 	%rd26, %rd3, -1;
	and.b64  	%rd4, %rd3, 3;
	setp.lt.u64 	%p5, %rd26, 3;
	mov.u32 	%r33, 0;
	mov.u64 	%rd35, 0;
	@%p5 bra 	LBB0_9;
// %bb.7:
	add.s64 	%rd34, %rd19, 8;
	sub.s64 	%rd6, %rd3, %rd4;
	mov.u32 	%r33, 0;
	mov.u64 	%rd35, 0;
LBB0_8:                                 // =>This Inner Loop Header: Depth=1
	ld.shared.u32 	%r17, [%rd34+-8];
	setp.eq.s32 	%p6, %r17, 1;
	selp.u32 	%r18, 1, 0, %p6;
	add.s32 	%r19, %r33, %r18;
	ld.shared.u32 	%r20, [%rd34+-4];
	setp.eq.s32 	%p7, %r20, 1;
	selp.u32 	%r21, 1, 0, %p7;
	add.s32 	%r22, %r19, %r21;
	ld.shared.u32 	%r23, [%rd34];
	setp.eq.s32 	%p8, %r23, 1;
	selp.u32 	%r24, 1, 0, %p8;
	add.s32 	%r25, %r22, %r24;
	ld.shared.u32 	%r26, [%rd34+4];
	setp.eq.s32 	%p9, %r26, 1;
	selp.u32 	%r27, 1, 0, %p9;
	add.s32 	%r33, %r25, %r27;
	add.s64 	%rd35, %rd35, 4;
	add.s64 	%rd34, %rd34, 16;
	setp.eq.s64 	%p10, %rd6, %rd35;
	@%p10 bra 	LBB0_9;
	bra.uni 	LBB0_8;
LBB0_9:
	ld.param.u64 	%rd18, [SYCL_class_monte_carlo_pi_kernel_param_1];
	cvt.u64.u32 	%rd2, %r8;
	setp.eq.s64 	%p11, %rd4, 0;
	@%p11 bra 	LBB0_12;
// %bb.10:
	shl.b64 	%rd28, %rd35, 2;
	add.s64 	%rd33, %rd19, %rd28;
	neg.s64 	%rd32, %rd4;
LBB0_11:                                // =>This Inner Loop Header: Depth=1
	.pragma "nounroll";
	ld.shared.u32 	%r28, [%rd33];
	setp.eq.s32 	%p12, %r28, 1;
	selp.u32 	%r29, 1, 0, %p12;
	add.s32 	%r33, %r33, %r29;
	add.s64 	%rd33, %rd33, 4;
	add.s64 	%rd32, %rd32, 1;
	setp.ne.s64 	%p13, %rd32, 0;
	@%p13 bra 	LBB0_11;
LBB0_12:
	shl.b64 	%rd29, %rd2, 2;
	add.s64 	%rd30, %rd18, %rd29;
	st.global.u32 	[%rd30], %r33;
LBB0_13:
	ret;
                                        // -- End function
}

