/*****************************************************************

    Copyright (C) 2002-2018 Codeplay Software Limited
    All Rights Reserved.

    Codeplay's ComputeCpp

********************************************************************/

/*!
  @file version.h

  @brief This file contains some common version related macros.

  This file is generated by CMake, do not modify it.
 */
#ifndef RUNTIME_INCLUDE_SYCL_VERSION_H_
#define RUNTIME_INCLUDE_SYCL_VERSION_H_

/** Full string version of ComputeCpp, including the edition and date
 */
#define __COMPUTECPP__ "CE 2.2.0 2020/09/19"

#define COMPUTECPP_VERSION_MAJOR 2
#define COMPUTECPP_VERSION_MINOR 2
#define COMPUTECPP_VERSION_PATCH 0

/** ComputeCpp version number as a string
 */
#define COMPUTECPP_VERSION_STRING \
  "2.2.0"

/** @cond COMPUTECPP_DEV */

/** @brief Specifies the edition of the ComputeCpp build
*/
#define COMPUTECPP_CE 1

/** COMPUTECPP_DEV @endcond */

#endif /* RUNTIME_INCLUDE_SYCL_VERSION_H_ */
